-- MySQL Script generated by MySQL Workbench
-- 10/11/16 12:50:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema url-shortener
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `url-shortener` ;

-- -----------------------------------------------------
-- Schema url-shortener
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `url-shortener` DEFAULT CHARACTER SET utf8 ;
USE `url-shortener` ;

-- -----------------------------------------------------
-- Table `url-shortener`.`browser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `url-shortener`.`browser` ;

CREATE TABLE IF NOT EXISTS `url-shortener`.`browser` (
  `browser-id` INT(11) NOT NULL AUTO_INCREMENT,
  `browser` VARCHAR(100) NOT NULL,
  `manufacturer` VARCHAR(100) NOT NULL,
  `browser-version` VARCHAR(100) NOT NULL,
  `browser-engine` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`browser-id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `url-shortener`.`device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `url-shortener`.`device` ;

CREATE TABLE IF NOT EXISTS `url-shortener`.`device` (
  `devices-id` INT(11) NOT NULL AUTO_INCREMENT,
  `device` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`devices-id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `url-shortener`.`user-role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `url-shortener`.`user-role` ;

CREATE TABLE IF NOT EXISTS `url-shortener`.`user-role` (
  `user-role-id` INT(11) NOT NULL AUTO_INCREMENT,
  `user-role` VARCHAR(100) NOT NULL,
  `is-admin` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`user-role-id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `url-shortener`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `url-shortener`.`user` ;

CREATE TABLE IF NOT EXISTS `url-shortener`.`user` (
  `user-id` BIGINT(100) NOT NULL AUTO_INCREMENT,
  `user-name` VARCHAR(1000) NOT NULL,
  `pass-word` VARCHAR(2000) NOT NULL,
  `is-verified` SMALLINT(1) NOT NULL,
  `user-login-attempts` INT(11) NOT NULL,
  `user-role-id` INT(11) NOT NULL,
  PRIMARY KEY (`user-id`),
  INDEX `FK_USER_USER_ROLE_idx` (`user-role-id` ASC),
  CONSTRAINT `FK_USER_USER_ROLE`
    FOREIGN KEY (`user-role-id`)
    REFERENCES `url-shortener`.`user-role` (`user-role-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `url-shortener`.`email-verification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `url-shortener`.`email-verification` ;

CREATE TABLE IF NOT EXISTS `url-shortener`.`email-verification` (
  `email-verification-id` BIGINT(100) NOT NULL,
  `email-verification-code` VARCHAR(100) NOT NULL,
  `email-verification-code-date` DATETIME NOT NULL,
  `user-id` BIGINT(100) NOT NULL,
  PRIMARY KEY (`email-verification-id`),
  INDEX `FK_EMAIL_USER_idx` (`user-id` ASC),
  CONSTRAINT `FK_EMAIL_USER`
    FOREIGN KEY (`user-id`)
    REFERENCES `url-shortener`.`user` (`user-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `url-shortener`.`forgot-password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `url-shortener`.`forgot-password` ;

CREATE TABLE IF NOT EXISTS `url-shortener`.`forgot-password` (
  `forgot-password-id` BIGINT(100) NOT NULL,
  `forgot-password-code` VARCHAR(100) NOT NULL,
  `forgot-password-code-date` DATETIME NOT NULL,
  `user-id` BIGINT(100) NOT NULL,
  PRIMARY KEY (`forgot-password-id`),
  INDEX `FK_FORGOT_USER_idx` (`user-id` ASC),
  CONSTRAINT `FK_FORGOT_USER`
    FOREIGN KEY (`user-id`)
    REFERENCES `url-shortener`.`user` (`user-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `url-shortener`.`os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `url-shortener`.`os` ;

CREATE TABLE IF NOT EXISTS `url-shortener`.`os` (
  `os-id` INT(11) NOT NULL AUTO_INCREMENT,
  `os` VARCHAR(100) NOT NULL,
  `manufacturer` VARCHAR(100) NOT NULL,
  `os-version` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`os-id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `url-shortener`.`url`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `url-shortener`.`url` ;

CREATE TABLE IF NOT EXISTS `url-shortener`.`url` (
  `url-id` BIGINT(100) NOT NULL,
  `url` VARCHAR(1000) NOT NULL,
  `short-url` VARCHAR(200) NOT NULL,
  `url-count` BIGINT(50) NOT NULL,
  `user-id` BIGINT(100) NOT NULL,
  PRIMARY KEY (`url-id`),
  INDEX `FK_URL_USER_idx` (`user-id` ASC),
  CONSTRAINT `FK_URL_USER`
    FOREIGN KEY (`user-id`)
    REFERENCES `url-shortener`.`user` (`user-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `url-shortener`.`url-analytics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `url-shortener`.`url-analytics` ;

CREATE TABLE IF NOT EXISTS `url-shortener`.`url-analytics` (
  `url-analytics-id` BIGINT(100) NOT NULL,
  `url-ip` VARCHAR(45) NOT NULL,
  `url-id` BIGINT(100) NOT NULL,
  `browser-id` INT(11) NOT NULL,
  `os-id` INT(11) NOT NULL,
  `device-id` INT(11) NOT NULL,
  PRIMARY KEY (`url-analytics-id`),
  INDEX `FK_URL_ANALYTICS_URL_idx` (`url-id` ASC),
  INDEX `FK_URL_ANALYTICS_BROWSER_idx` (`browser-id` ASC),
  INDEX `FK_URL_ANALYTICS_OS_idx` (`os-id` ASC),
  INDEX `FK_URL_ANALYTICS_DEVICE_idx` (`device-id` ASC),
  CONSTRAINT `FK_URL_ANALYTICS_BROWSER`
    FOREIGN KEY (`browser-id`)
    REFERENCES `url-shortener`.`browser` (`browser-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_URL_ANALYTICS_DEVICE`
    FOREIGN KEY (`device-id`)
    REFERENCES `url-shortener`.`device` (`devices-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_URL_ANALYTICS_OS`
    FOREIGN KEY (`os-id`)
    REFERENCES `url-shortener`.`os` (`os-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_URL_ANALYTICS_URL`
    FOREIGN KEY (`url-id`)
    REFERENCES `url-shortener`.`url` (`url-id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'This Table will Store Details of Each Click when Any Shorten URL will come to serve.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
